name: dartless_server
version: 0.0.1
description: A server that manages clueless games
author: Brian G. <mixolyde@gmail.com>
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  intl: any
  http: any
  redstone: any
  redstone_mapper_pg: any
  redstone_web_socket: any
  math: any
dev_dependencies:
  unittest: any
